import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Landing from '@/component/home/Home'
import Textanimation from '@/component/data/Text'
import Bootstrap from '@/component/bootstrap/Bootstrap'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Avo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {/* <Landing/> */}
        {/* <Textanimation /> */}
        <Bootstrap/>
        
      </>
    </>
  )
}
